### ISSUE TITLE
so is this JRakLibPlus ready to be integrated?

### ISSUE THREAD

**Issue by DefinitlyEvil** [jython234/JRakLibPlus#1]

**Comment by DefinitlyEvil** [comment]
I faild to connect using MCPE 0.12.1 alpha. xD

**Comment by drtshock** [comment]
Would love to know if you guys need any help getting this updated so we can get PE clients connected on the new version :)

**Comment by alejzeis** [comment]
@DefinitlyEvil @drtshock Rewrite has been merged into master, should be ready for general use.

**Comment by DefinitlyEvil** [comment]
@jython234 I'm very interested in ur JRakLib client library cuz we will need it now for connecting to PE servers.

**Comment by alejzeis** [comment]
@DefinitlyEvil I plan on making a client for JRakLibPlus aswell, but it may
take some time.

**Comment by DefinitlyEvil** [comment]
@jython234 Sure.
