### ISSUE TITLE
Session SendPacket

### ISSUE THREAD

**Issue by net32** [jython234/JRakLibPlus#4]
I'm trying to send a EncapsulatedPacket and does not work

```
            EncapsulatedPacket pk = new EncapsulatedPacket();
            pk.reliability = Reliability.RELIABLE;
            pk.payload = new byte[0];
            session.sendPacket(pk);
```

**Comment by net32** [comment]
I have to use new CustomPacket()?

Please show me a example

**Comment by alejzeis** [comment]
If sending encapsulated packets in a session use addToQueue()

**Comment by net32** [comment]
dude, help me, i am trying to send packet = Reliability.RELIABLE, and never works, Argh i am crazy!!!

```
EncapsulatedPacket ep = new EncapsulatedPacket();
ep.reliability = Reliability.RELIABLE;
ep.payload = BufferOfDataPacket;
session.sendPacket(ep);
```

i am trying to send with and without appened ByteDataPack (0x8e)!

Dude helpe, show me a simple example, i am thinking its a problem with API of JRakLibPlus

**Comment by net32** [comment]
argh was to be used session.addPacketToQueue()!

I will crush you! kkkk just kidding 

solved!
